#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-nginx
prepare_service 20-llng
SERVICE_NAME="lemonldap-ng"

transform_var file MODE
if [ "${MODE,,}" = "all" ]; then
    print_debug "Container Mode: ALL - Enabling all modes and generating environment variables for each mode"
    transform_var file \
                        ENABLE_API \
                        ENABLE_HANDLER \
                        ENABLE_MANAGER \
                        ENABLE_PORTAL \
                        ENABLE_TEST

    _container_build_env " \
                            20-llng/ENABLE_API=${ENABLE_API:-"TRUE"} \
                            20-llng/ENABLE_HANDLER=${ENABLE_HANDLER:-"TRUE"} \
                            20-llng/ENABLE_MANAGER=${ENABLE_MANAGER:-"TRUE"} \
                            20-llng/ENABLE_PORTAL=${ENABLE_PORTAL:-"TRUE"} \
                            20-llng/ENABLE_TEST=${ENABLE_TEST:-"TRUE"} \
                            10-nginx/NGINX_ENABLE_APPLICATION_CONFIGURATION=TRUE \
                            10-nginx/NGINX_SITE_ENABLED=api,handler,manager,portal,test \
                         "
    ENABLE_API=${ENABLE_API:-"TRUE"}
    ENABLE_HANDLER=${ENABLE_HANDLER:-"TRUE"}
    ENABLE_MANAGER=${ENABLE_MANAGER:-"TRUE"}
    ENABLE_PORTAL=${ENABLE_PORTAL:-"TRUE"}
    ENABLE_TEST=${ENABLE_TEST:-"TRUE"}
else
    modes=$(echo "${MODE,,}" | tr "," "\n")
    for mode in $modes; do
        case "${mode,,}" in
            "api" | "handler" | "manager" | "portal" | "test")
                print_debug "Enabling Container Mode for: ${mode^}"
                set -x
                _container_build_env "10-nginx/NGINX_ENABLE_APPLICATION_CONFIGURATION=TRUE"
                _container_build_env "20-llng/ENABLE_${mode^^}=TRUE"
                _container_build_env "10-nginx/NGINX_SITE_ENABLED=\${NGINX_SITE_ENABLED},${mode,,}"
                set +x
            ;;
            *)
                print_error "Unknown 'MODE' environment variable - exitting.."
                exit 1
            ;;
        esac
    done
fi

liftoff
