#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
#source /container/base/defaults/*-monitoring
#source /container/defaults/10-nginx
prepare_service 10-nginx
prepare_service 20-llng
SERVICE_NAME="lemonldap-ng"

llng_bootstrap_filesystem
llng_setup_container_mode
llng_bootstrap_configuration
llng_configure_configuration
llng_configure_logging

if var_true "${CONTAINER_ENABLE_FIREWALL}" && var_true "${CONTAINER_ENABLE_FAIL2BAN}" ; then llng_configure_fail2ban_llng ; fi
llng_configure_api
llng_configure_handler
llng_configure_manager
llng_configure_portal
llng_configure_test
llng_write_config
llng_configure_webserver
llng_configure_socket

chown -R "${NGINX_USER}":"${NGINX_GROUP}" "${DATA_PATH}"

create_zabbix llng

custom_files "${CONTAINER_CUSTOM_PATH}" "${NGINX_WEBROOT}" "${NGINX_USER}" "${NGINX_GROUP}"

liftoff
