#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-nginx
prepare_service 20-llng
SERVICE_NAME="lemonldap-ng"

llng_setup_container_mode
llng_bootstrap_filesystem
llng_configure_instance
llng_configure_instance_global_configuration
llng_configure_api
llng_configure_handler
llng_configure_manager
llng_configure_portal
llng_configure_test
llng_configure_fail2ban
llng_configure_webserver
llng_write_instance_config
chown -R "${NGINX_USER}":"${NGINX_GROUP}" "${DATA_PATH}"
create_zabbix llng
custom_files "${CONTAINER_CUSTOM_PATH}" "/usr/share/lemonldap-ng/" "${NGINX_USER}" "${NGINX_GROUP}"

liftoff
