services:
  lemonldap-app:
    image: tiredofit/lemonldap:latest
    container_name: lemonldap-app
    volumes:
      - ./data/etc/lemonldap-ng:/etc/lemonldap-ng
      - ./data/var/lib/lemonldap-ng/conf:/var/lib/lemonldap-ng/conf
      - ./data/var/lib/lemonldap-ng/sessions:/var/lib/lemonldap-ng/sessions
      - ./data/var/lib/lemonldap-ng/psessions:/var/lib/lemonldap-ng/psessions
      - ./logs:/www/logs
      #- ./assets/custom:/assets/custom
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=lemonldap-app

      - SETUP_TYPE=AUTO

      - API_HOSTNAME=api.manager.sso.example.com
      - MANAGER_HOSTNAME=manager.sso.example.com
      - PORTAL_HOSTNAME=sso.example.com
      - HANDLER_HOSTNAME=handler.sso.example.com

      - LOG_TYPE=FILE
      - LOG_LEVEL=debug
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true

