services:
  lemonldap-handler-app:
    image: docker.io/nfrastack/lemonldap:latest
    container_name: lemonldap-handler-app
    volumes:
    - ./data/etc/lemonldap-ng:/etc/lemonldap-ng
    - ./logs:/www/logs
    environment:
    - TIMEZONE=America/Vancouver
    - CONTAINER_NAME=lemonldap-handler-app

    - MODE=HANDLER

    - DOMAIN_NAME=example.com
    - HANDLER_HOSTNAME=handler.sso.example.com
    - HANDLER_ALLOWED_IPS=172.16.1.0/24,192.168.0.1,10.0.0.0/12

    - CONFIG_TYPE=REST
    - REST_HOST=https://sso.example.com/index.psgi/config
    - REST_USER=dwho
    - REST_PASS=dwho
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true

