#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-llng
SERVICE_NAME="lemonldap-ng-handler"

check_container_initialized
check_service_initialized init

### Check to see if Enabled/Disabled
if var_true "${HANDLER_SOCKET_TCP_ENABLE}" ; then
    _socket="-l 0.0.0.0:"${HANDLER_SOCKET_TCP_PORT}
else
    _socket="-s /var/run/llng-fastcgi-server/llng-fastcgi.sock"
fi
set -x
echo "${LOG_TYPE} LOG TYPE "
if [ "${LOG_TYPE,,}" != "console" ] ; then
    silent_arg=silent
fi
set +x
case "${HANDLER_PROCESSES,,}" in
    auto )
        HANDLER_PROCESSES=$(nproc)
    ;;
    ''|*[!0-9]*)
        print_error "Invalid HANDLER_PROCESSES value, must be a number"
        liftoff
    ;;
    0)
        print_error "Invalid HANDLER_PROCESSES value, must be greater than zero"
        liftoff
    ;;
esac

liftoff


print_start "Starting (${HANDLER_PROCESSES}) LemonLDAP FastCGI Server $(grep -o "ADD: LemonLDAP:NG v.* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}') Handlers"
set -x
${silent_arg} exec sudo -u "${NGINX_USER}" \
                                /usr/local/bin/llng-fastcgi-server \
                                    ${_socket} \
                                    -n ${HANDLER_PROCESSES} \
                                    -foreground
set +x