#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-llng
SERVICE_NAME="lemonldap-ng-handler"

check_container_initialized
check_service_initialized init

if [ "${LOG_TYPE,,}" != "console" ] || { [ -n "${HANDLER_LOG_TYPE}" ] && [ "${HANDLER_LOG_TYPE,,}" != "console" ]; }; then
    silent_arg=silent
fi

case "${HANDLER_PROCESSES,,}" in
    auto )
        HANDLER_PROCESSES=$(nproc)
    ;;
    ''|*[!0-9]*)
        print_error "Invalid HANDLER_PROCESSES value, must be a number"
        liftoff
    ;;
    0)
        print_error "Invalid HANDLER_PROCESSES value, must be greater than zero"
        liftoff
    ;;
esac

# Socket selection logic
if [ -n "${HANDLER_SOCKET}" ]; then
    if [[ "${HANDLER_SOCKET}" == unix:* ]]; then
        _socket="-s ${HANDLER_SOCKET#unix:}"
    elif [[ "${HANDLER_SOCKET}" == *:* ]]; then
        port="${HANDLER_SOCKET##*:}"
        _socket="-l 0.0.0.0:${port}"
    else
        _socket="-s ${HANDLER_SOCKET}"
    fi
else
    case "${HANDLER_LISTEN_SOCKET_TYPE,,}" in
        "path" | "unix" )
            _socket="-s ${HANDLER_LISTEN_SOCKET_PATH}"
        ;;
        "tcp" )
            _socket="-l 0.0.0.0:${HANDLER_LISTEN_SOCKET_TCP_PORT}"
        ;;
        "both" )
            _socket="-s ${HANDLER_LISTEN_SOCKET_PATH} -l 0.0.0.0:${HANDLER_LISTEN_SOCKET_TCP_PORT}}"
        ;;
        *)
            case "${DEFAULT_SOCKET_TYPE,,}" in
                "path" | "unix" )
                    _socket="-s ${DEFAULT_SOCKET_PATH}"
                ;;
                "both" )
                    _socket="-s ${DEFAULT_SOCKET_PATH} -l 0.0.0.0:${DEFAULT_SOCKET_TCP_PORT}"
                ;;
                "tcp" | *)
                    _socket="-l 0.0.0.0:${DEFAULT_SOCKET_TCP_PORT}"
                ;;
            esac
        ;;
    esac
fi

liftoff


print_start "Starting (${HANDLER_PROCESSES}) LemonLDAP FastCGI Server $(grep -o "ADD: LemonLDAP:NG v.* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}') Handlers"
${silent_arg} exec sudo -u "${NGINX_USER}" \
                                /usr/local/bin/llng-fastcgi-server \
                                    ${_socket} \
                                    -n ${HANDLER_PROCESSES} \
                                    -foreground