#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-llng
SERVICE_NAME="lemonldap-ng-handler"

check_container_initialized
check_service_initialized init

### Check to see if Enabled/Disabled
if var_true "${HANDLER_SOCKET_TCP_ENABLE}" ; then
    _socket="-l 0.0.0.0:"${HANDLER_SOCKET_TCP_PORT}
else
    _socket="-s /var/run/llng-fastcgi-server/llng-fastcgi.sock"
fi

if [ "${LOG_TYPE,,}" != "console" ] ; then
    silent_arg=silent
fi

liftoff

print_start "Starting (${HANDLER_PROCESSES}) LemonLDAP FastCGI Server ${LEMONLDAP_VERSION} Handlers"
${silent_arg} exec sudo -u llng \
                                /usr/sbin/llng-fastcgi-server \
                                    ${_socket} \
                                    -n ${HANDLER_PROCESSES} \
                                    -foreground
